### ISSUE TITLE
Replace individual ssl certificates with one multi-san cert.

### ISSUE THREAD

**Issue by hgputnam** [mountetna/monoetna#1014]
We have a number of dtaging certs expiring. I have set up and submitted the CSR for a multi-san cert which will work for:

janus-stage.dsco.ucsf.edu
magma-stage.dsco.ucsf.edu
metis-stage.dsco.ucsf.edu
polyphemus-stage.dsco.ucsf.edu
timur-stage.dsco.ucsf.edu
vulcan-stage.dsco.ucsf.edu
airflow.dsco.ucsf.edu
grafana.dsco.ucsf.edu
janus.ucsf.edu
magma.ucsf.edu
metis.ucsf.edu
polyphemus.ucsf.edu
portainer.dsco.ucsf.edu
prometheus.dsco.ucsf.edu
timur.ucsf.edu
vulcan.ucsf.edu

**Comment by hgputnam** [comment]
I am updating hulao on Sunday as part of the shutdown. IT Sec will rescan on Monday or Tuesday and issue the cert. I may not get them installed until after 9/15 but nothing will break until 9/30.

**Comment by hgputnam** [comment]
@coleshaw - once done we may want to discuss replacing the /etc/ssl/app_name folders with just /etc/ssl since we only have one cert after this...

**Comment by coleshaw** [comment]
Okay, that will be awesome! I can make that change in the Apache conf file when it's available.

**Comment by coleshaw** [comment]
Looks like the portainer.dsco.ucsf.edu cert expires on Sept 20th

**Comment by coleshaw** [comment]
This is looking great -- Harry put this in yesterday. :tada:
