### ISSUE TITLE
Shut down old janus vm for out of space condition

### ISSUE THREAD

**Issue by hgputnam** [mountetna/monoetna#1042]
I just shut down old Janus. Let me know if there is any fallout.

**Comment by coleshaw** [comment]
Everything still seems to be running okay in production ...

I think you can also shut down iliad (which had old polyphemus on it), I don't think we're using that, either.

**Comment by hgputnam** [comment]
OK, old iliad vm is also shut down now.

**Comment by coleshaw** [comment]
Stuff seems to still be running fine, will close this out for now.
