### ISSUE TITLE
polyphemus.ucsf.edu is not available outside the VPN?

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#1055]
Hi @hgputnam , not sure if some IT network configuration has changed recently, but it appears that `polyphemus.ucsf.edu` is not available outside of the VPN (? at least it seems that way to me). Can you configure that like the other root-level apps (Vulcan, Timur, Magma, Metis, Janus), so that it can be used outside of the VPN?

Thanks!

**Comment by hgputnam** [comment]
Hi @coleshaw - the DNS cname is available outside the VPN but it is resolving to iliad.ucsf.edu (169.230.134.24). Inside the VPN, the cname does resolve to hulao.dsco.ucsf.edu whis is what we want correct? If true, I will need to put in a deletion request for the existing external cname (resolves to iliad) followed by a new request for an external cname that resolves to hulao. Please confirm and I will get that started.

**Comment by coleshaw** [comment]
Hmmmm, interesting. Yes, the external cname should also resolve to hulao. I wonder if that means folks have been editing configs on different databases, depending on if they are on VPN or not ... ick, let me check.

**Comment by coleshaw** [comment]
And to clarify, yes please put in the CNAME requests to delete the iliad one, and then a new one to point to hulao :smile: Sorry I got distracted by thinking about the potential implications.

**Comment by coleshaw** [comment]
Okay, good to know :+1:
