### ISSUE TITLE
Gnomon SSL -- add to our common cert

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#1105]
Now that we have the DNS CNAME added, we'd like to add Gnomon to the common / shared SSL cert.

**Comment by hgputnam** [comment]
Hi @coleshaw - before I submit, is gnomon.dsco.ucsf.edu correct?

Thanks.

**Comment by coleshaw** [comment]
@hgputnam , it should be `gnomon.ucsf.edu`. Sorry I forgot to clarify in the issue!

**Comment by hgputnam** [comment]
OK,no problem.

**Comment by coleshaw** [comment]
Thank you for checking -- :pray:

**Comment by hgputnam** [comment]
Oh, and this is both internal and external to UCSF network?

**Comment by coleshaw** [comment]
Yes, should be both internal and external. I think the CNAME is set up that way already.

**Comment by hgputnam** [comment]
RITM0371015 submitted for new cert.

**Comment by coleshaw** [comment]
@hgputnam , have you heard back from IT about the cert?
