### ISSUE TITLE
Virtual Machines Question

### ISSUE THREAD

**Issue by hgputnam** [mountetna/monoetna#1148]
Hi Folks

I just reviewed the vm stuff. The only "old" vms that are currently running are magma & magma-second. Can these be shut down or shall I put those on the list of things to move during our outage?

**Comment by coleshaw** [comment]
I believe those can be shut down. Magma is running in the Swarm, and I have no idea what we used magma-second for...but apparently it isn't critical for production.

**Comment by graft** [comment]
Confirming, I don't think there is anything important running there. Magma-second was an ancient second production instance of magma, deprecated for years.

**Comment by hgputnam** [comment]
OK, I am shutting them down. Let me know if they need to come back up.

**Comment by hgputnam** [comment]
Oh, one other one. Does anyone know if cbc-master is needed?

**Comment by coleshaw** [comment]
That one is no longer needed, but it would probably be good to back up the developer account / chef directory (I don't quite recall what that is, and can't get into the box anymore -- I think it's `cbc-chef/` under the developer home directory?). Keeping a backup copy of the cookbooks and roles might be helpful, in case we have some credentials we left there.

**Comment by hgputnam** [comment]
OK, I found a /home/developer with a bunch of chef stuff.  I tarred it up and placed a copy in @graft and @coleshaw home directories on C4. I also put a copy in the backup area of the new storage server. Lastly, the vm is now shut down. Let me know if it turns out we need it...

**Comment by coleshaw** [comment]
Thank you!
