### ISSUE TITLE
Create repository with Docker node Ansible scripts

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#1159]
@hgputnam , can you put your Ansible scripts for configuring our docker nodes into GitHub somewhere? Preferably a repository under `mountetna` organization, if you can (or let me know and I  or @graft can create one for this purpose)...

Thanks!

**Comment by graft** [comment]
Started here: https://github.com/UCSF-TI/MtEtna-Sysadmin, maybe just needs updating

**Comment by hgputnam** [comment]
That looks like an old science experiment. This is the one I was thinking of, Zach used to update stuff from time to time: https://github.com/UCSF-TI/dsco-ansible

**Comment by hgputnam** [comment]
I think Saurabh, Cole, & Gabi currently have access. Let me know if I should add Dan or others...
