### ISSUE TITLE
Etna CLI bug with model / attribute definitions being caught as duplicates

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#134]
@corps -- weird bug for you with the CSV model stuff.

I was playing around with it, and it's really neat. I downloaded my local copy of MVIR1, but right off the bat, got an error in the command line:

```
$ etna administrate models add mvir1
Input file mvir1_models_project_tree.csv is invalid:
  * Error detected on line 314: Attribute restricted of model cytof_pool has duplicate definitions!
```

On the server this attribute is valid and not duplicated. The CSV for `cytof_pool` has no duplicated rows, and there is only a single `restricted` attribute in the definition.

However, it appears that the problem is exclusively with any link relationship (i.e. pools), where the non-pool model is defined first in the CSV, and any attribute that appears below the link attribute leaks into the pool model template. For example, when you have in the `cytof` model:

cytof_pool | link | cytof_pool |   | CyTOF pool
-- | -- | -- | -- | --
restricted | boolean |   |   | Restricted

You'll get the error. But if you flip the two rows in `cytof` to:

restricted | boolean |   |   | Restricted
-- | -- | -- | -- | --
cytof_pool | link | cytof_pool |   | CyTOF pool

The issue goes away and the validator declares the CSV as okay. If you declare the pool model first in the CSV, there is no error.

In the code, it appears that the `restricted` attribute from `cytof` somehow leaks into the attributes for `cytof_pool`?

**Comment by corps** [comment]
I may have a fix for this?  In my latest branch.

**Comment by corps** [comment]
I'll check.

**Comment by coleshaw** [comment]
:+1: that would be cool!

**Comment by corps** [comment]
Ok, awesome, thanks for this bug report, fix coming in my new branch!  Confirmed with test
