### ISSUE TITLE
Validations are "too long" for spreadsheets?

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#140]
So I don't know if this is going to be a problem with Excel, but when I open up an MVIR1 CSV in LibreOffice Calc, I get a warning about the cell contents for `rna_seq` `gene_counts` and `gene_tpm` validation arrays being too long, so they get truncated. Then, when the tool calculates changes, it thinks that I've changed that set of validation options and I suspect it's going to update and remove a bunch of gene names (it only sees up to `ENSG00000111199`, but should be up to `ENSG00000283699`).

When uploading the CSV to Google Spreadsheets, it actually leaves those cells blank -- no validation `options` at all ... ? Kind of unexpected. Downloading the sheet shows the cells as blank, so the information is actually lost, not just hidden. Will the tool think that's an update and wipe out the validations? If we're expecting that to be part of the workflow, maybe we need to build in some sort of "don't update long validations" protection into the sync?

@gfragiadakis @dtm2451 , could one of you test out the CSV that I posted in Slack on a Mac with Excel, and see if cells P235 and P299 get truncated or what they look like?

@graft @corps FYI.

**Comment by dtm2451** [comment]
I get this first:
![image](https://user-images.githubusercontent.com/38870347/98711852-6422a700-233a-11eb-9246-51ae77cd148c.png)

And then ENSG00000091436 is the last gene for both P235 & P***300**. (Hopefully your 299 was meant to be 300 and this isn't some additional Excel bug we'd need to plan around!)

**Comment by coleshaw** [comment]
Thanks for checking! Hmm.....interesting. It's P299 on both my local copy, Google spreadsheets, and a text editor -- is your G300 gene_tpm, or a different attribute name? It's a bit disturbing that our row numbers are different, from the same CSV file...

**Comment by dtm2451** [comment]
It's gene_tpm.  But then actually the row below for both of these has some weird encoding of ENSGs...
![image](https://user-images.githubusercontent.com/38870347/98722627-262b8000-2346-11eb-8445-1c26a37aa96e.png)

**Comment by dtm2451** [comment]
This is ugly =/

**Comment by coleshaw** [comment]
Oh ew, looks like Excel inserted the overflow data into a new row?!!?? Harumph...

**Comment by coleshaw** [comment]
I suspect that extra line will break the CLI more than the empty validation cells, though neither is particularly a great outcome...

**Comment by dtm2451** [comment]
Yea, this is really... unfortunate.

Perhaps those cells can be filled in, instead, with a link to some file that holds all gene names?  That'd get us around the cell-too-big issue without turning off this validation, but it does add an extra step for both users and the CLI.
