### ISSUE TITLE
Add pylint checks to Vulcan scripts

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#302]
I'm wondering if, at a minimum, we should add pylint to CI to check over the Vulcan scripts? Might be useful, to catch any syntax or simple errors, since we don't have explicit tests for those individually.

**Comment by corps** [comment]
I do agree.  Mostly to fix serious errors, not to complain on simple style issues.

**Comment by corps** [comment]
Although, worth nothing, _we already have this_ in the form of the checker command.  We could easily just run the checker script against all vulcan scripts in ci.  Wouldn't be impossible.

In the future I imagine that before a user uploads a custom script the checker would check and route out any issues.

**Comment by graft** [comment]
The issue we ran into today was that the checker encounters normal syntax errors in addition to DSL violations and fails as a result (e.g. I forgot a `:` after `else`) - getting feedback at runtime is not in itself terrible (after all, no point in checking a piece of code no one will ever run again), but the feedback needs to be less opaque; if the checker is responsible for catching all syntax errors, it should report them to the user in a way that helps resolve the bugs. Currently I think this can only be done using archimedes-run, which if you are just testing your python via the vulcan UI involves: (1) find a bug, (2) carefully pick out the inputs required to reproduce, (3) run using archimedes-run to catch python syntax errors. Somewhat onerous...

**Comment by corps** [comment]
Right.  So, there's three issues then -- one, validating that our scripts we check into master get validated during CLI.  All we need to fix that is write an rspec that globs our scripts and executes that archimedes-checker.

The issue of reporting syntax errors or other script errors back to the user -- probably we can improve, but I ind of really doubt there is much can be done other than dumping the stack.  Why do I suspect that most of our end users are not going to actually fix scripts that have issues, but simply report them to someone who can (in which case a stack trace is really all that person wants)?

The issue of linting files as a scripter writes new scripts -- well, that is an ide configuration issue.  The checker itself is nothing but a pylint plugin which, incidentally, can be configured to run automatically as part of any pylint integration for free, although it takes some setup on the engineer in general depending on their ide.

**Comment by corps** [comment]
Err, sorry.  Yeah, I mean overall the error experience is something that can be improved I think.

**Comment by graft** [comment]
>  Why do I suspect that most of our end users are not going to actually fix scripts that have issues, but simply report them to someone who can (in which case a stack trace is really all that person wants)?

Stack traces would be great, but don't seem to apply to syntax errors, which have to be caught before the DSL is approved and there is any stack at all to dump. I assume that the checker can generate a normal python syntax error like the default python linter does (SyntaxError and IndentationError etc.), so we should just expose that... for runtime errors I can't imagine what would be more useful than a stack trace.
