### ISSUE TITLE
Sort group inputs for stable appearance?

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#326]
When selecting / deselecting grouped inputs (Select Records step), the inputs seem to jump around in the drawer based off of completion status? Unclear, but it is a big awkward to see them changing order in the list. Perhaps we should sort them alphabetically.

**Comment by coleshaw** [comment]
Note that this only seems to happen on a previously submitted (COMPLETE) step, and the "blank" option is always moved to the bottom of the group.

**Comment by dtm2451** [comment]
:+1: I definitely have seen this too.
