### ISSUE TITLE
issues & ideas raised after recent Vulcan back-end update

### ISSUE THREAD

**Issue by dtm2451** [mountetna/monoetna#329]
Recording these here...

Issues:
- [x] need to manually refresh the page to see the umap show up [likely check this box after testing]
- [x] Hammer nolonger electrified during running.
- [x] Gene input not work for coloring -- 2nd selection box does not show up.
- [ ] Needing to hit run right away may be confusing. (Previously, the first cell (a magma query to populate selection options) was proactively run.) 
- [x] Clicking `Workflow` button from the Vignette page does not navigate properly back to the workflow page because the project_name was not filled in to the url: https://vulcan.development.local/null/workflow.
- [x] magma query parameterization problem at `import into scanpy` step when there are many records
- [x] Clocks did not move continuously while steps were running. The running animation seemed short-lived and only applied to the first step after "Run" was hit.

Enhancements:
- [ ] Zoom/window button, with the plotly buttons, that opens a new window with just the UMAP widget.
- [x] Changes to the color-by output could automatically trigger running for live-ish plot updates... they do now for previously loaded options
- [x] Text box with live typing-based filtering in the experiment/tissue/fraction multi-selects. (Togglable on/off at UI-engineer level could be nice?)
- [x] Perhaps the workflow vignette could be an .md iframe

**Comment by coleshaw** [comment]
I think "Needing to hit run right away" may change anyways as we add in support for more projects ... I think we'll have to create a widget before "Run" but after you click on a card, that says which project you want to run the workflow for.

**Comment by dtm2451** [comment]
Gonna close this as the remaining "issue" is not an actual issue and the remaining enhancement is not a high priority item.
