### ISSUE TITLE
Vulcan sometimes jumps back and hangs at the "Confirm record names" step

### ISSUE THREAD

**Issue by dtm2451** [mountetna/monoetna#391]
Sometimes, after all steps had been completed, the system comes back to the "Confirm record names" step and hangs there with clicking the `Run` button doing nothing.  A refresh makes download buttons momentarily appear, and download actually works if you're fast enough to click it!  But then then everything goes away and returns to appearing stuck on the "Confirm Records Step".

**Comment by coleshaw** [comment]
Do you have a way to reliably reproduce this? You mean when the entire workflow finishes and you're seeing a UMAP??

**Comment by dtm2451** [comment]
I'm not sure right now how to pin it down reproducibly. Like #392, it stopped happening for me was when I re-deployed, but there is zero chance that my plot_umap.py script update had a direct effect. Also @bsamad didn't seem to have this issue, but I think Tristan may have.

This is one of the ones that Zach got to see on Friday.  But it happened after color-by selection, around the time that you would have seen the UMAP.  Instead, the UMAP never popped up at all, contrary to the download buttons which only popped up momentarily.

**Comment by dtm2451** [comment]
Just noting that Tristan reported a similar behavior today in slack-#vulcanfixes upon loading in his saved workflow.
