### ISSUE TITLE
Vulcan sometimes does not move past the "Record Selection" step

### ISSUE THREAD

**Issue by dtm2451** [mountetna/monoetna#392]
Sometimes Vulcan does not appear to do anything after a user makes record selections and clicks `Run`.
POSTs get returned with 200 statuses, but the "Interpret record selection inputs." step is not run.

**Comment by coleshaw** [comment]
Do you have a way to reliably reproduct this? Does it only happen on production, and not on development or locally?

**Comment by dtm2451** [comment]
This one does happen locally in Dev. (I'm not sure about #391... I'd never seen that one locally myself.) Remember when I was slacking you about a weird bug that seemed to happen sometimes when I would re-build Vulcan, and so I remade my docker images?  That was this.  Apparently it wasn't something unique to my system as it happened in production as well!

**Comment by dtm2451** [comment]
Noting again, this is one of the bugs that @corps saw live.

**Comment by coleshaw** [comment]
Very odd. I'll let Zach dig into it since he saw it live....this one made me think of a graph issue that I thought I fixed, where not all step dependencies were being calculated correctly on the server. :shrug: Maybe I didn't fully fix it, or it's a completely unrelated issue.
