### ISSUE TITLE
Vulcan data transformation widget -- performance constraints?

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#765]
Trying to use the Vulcan data transformation widget and visualization workflow with full gene expression matrices, and couple of performance issues:

* Browser complains when trying to open the table, that a script is slowing down the page. So perhaps we need to tweak the table code somehow.
* Cannot commit and run with the raw data, because the data frame causes local storage to exceed the max permissible amount (on FF at least).
* Downloading large amounts of data from Magma causes the Magma proxy to time out (i.e. all gene expression matrices for IPI), and the Archimedes cell throws a Python exception.

So, not sure what folks will expect to be able to input into Vulcan visualizations, but we will have to work around some stuff for large data sets. Or, is there some limit in which we say, you should be using a command line / full analysis pipeline, and Vulcan is just for simple exploration?

**Comment by coleshaw** [comment]
Definitely some tweaking of the [table performance is possible](https://handsontable.com/docs/performance/#overview).

Perhaps we can investigate IndexDB in lieu of local storage, as well.

**Comment by corps** [comment]
@coleshaw If you are looking into IndexedDB, I highly recommend https://dexie.org/

It has a typescript bindings, and the wrapper is 'minimal' -- it provides the most useful aspects of the base api in a convenient way without hiding underlying pieces.

**Comment by graft** [comment]
I'm loathe to boot up a method to store gigabytes of data locally and run calculations on them in the browser, which seems like a bad pattern leading to many headaches. If possible, it might be better to move most of the calculation server-side - i.e., you could just show a head of the table with a sample of the data, allow them to compose their transformation calculations, then ship the formulas from the first row or some such. Not sure how you might effect running the table calculations on the server - either running the handsontable js or running an equivalent python lib (e.g. @vinci1it2000/formulas) - since handsontables' HyperFormulas claims to be fully compatible with Excel, this might work, though I imagine there will be some holes.

**Comment by coleshaw** [comment]
Hm, that's a good point. But interpreting partial equations on the server seems complicated. How would you deal with things like `sum across an entire column`, or other formulas that span a range?  Do you make an assumption about the range?

Is there an assumption that folks will never use formulas to fill holes, but only for populating entire columns?

**Comment by graft** [comment]
Yeah, these all seem difficult to solve. Ideally what we seek is giving the user the ability to specify vector operations on columns which we can then apply server-side; using spreadsheet notation allows far more fine-grained interactions, so it's not quite appropriate to that task. Airtable seems to [support formulas of this kind](https://support.airtable.com/hc/en-us/articles/360035357753-Basic-calculations-using-the-formula-field)...

**Comment by coleshaw** [comment]
I do think that we'll have to move the calculation to the server for large data frames, but I would prefer to use Excel-like formulas over some custom / Airtable-like thing, just because then it seems like we're inventing our own programming language, again...at least with Excel formulas, there are lots of libraries and examples on the internet.

Moving the calculation to the server does wind up leaving an additional responsibility to the CWL workflow author, in that they then have to also correctly wire in the "translate vector operation" python step into their workflow. Perhaps there is no way around that :shrug:

**Comment by coleshaw** [comment]
> Moving the calculation to the server does wind up leaving an additional responsibility to the CWL workflow author, in that they then have to also correctly wire in the "translate vector operation" python step into their workflow.

I guess looking at the visualization stuff, this is the same requirement ... you have to include the right Python step post-visualization and wire it in properly to make it work, so perhaps not a big issue.

**Comment by graft** [comment]
I am thinking about how input and output steps should have pre- and
post-hooks that run automatically in python anyway, to avoid such
boilerplate.
