### ISSUE TITLE
Vulcan: Copy figure should strip all tags

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#790]

**Comment by coleshaw** [comment]
@graft , so I think the weird thing about doing this (which you brought up at the meeting), would be that the copy woudln't appear in the page, by default, because the `public` tag would be gone and the copied figure would get filtered out... :thinking:

**Comment by graft** [comment]
Hmm good point. One possibility: the copy button clears tags and sets the filter to the name of the copied figure (so mostly only old and new would show up)

**Comment by coleshaw** [comment]
Hm, so that would also involve a change to "text search || tags" instead of the current "text search && tags" ? Is that counter to the general search UX pattern?

Or perhaps we always show all of a user's own figures, regardless of tag or text search? Seems perhaps burdensome...

**Comment by coleshaw** [comment]
Hm, but by resetting the tag search, wouldn't you also get all the figures, so it would explode the figures cards (try this on IPI -- you'd go from like 4, to 20+ right now)...? Would seem even more confusing, if you copied a public figure, and you all of a sudden see a ton of them?
 
 
-----Original Message-----
