### ISSUE TITLE
Magma should let you query file size

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#898]
In addition to `md5`, perhaps should let Magma retrieve file sizes for linked Metis files. Would make project data compilation a bit easier...

**Comment by graft** [comment]
This might just be satisfied via #894 which would let you just ls -l the corresponding Magma file.

**Comment by coleshaw** [comment]
Or exporting from the Query UI to excel (or Vulcan) to do such calculations

**Comment by graft** [comment]
hmm makes sense - i forgot we also started caching this in the DB so this is much easier to deliver
