### ISSUE TITLE
Path to always use latest images in vulcan

### ISSUE THREAD

**Issue by dtm2451** [mountetna/monoetna#939]
For development purposes, it would be incredibly helpful to be able to simply refresh the page and re-`Run`, after editing scripts and rebuilding vulcan/archimedes.  Especially considering that the 'Update dependencies' option does not work in dev currently because it targets `:production` images.  Currently, I need to `create figure` anew each time.

**Comment by coleshaw** [comment]
Hm, update-dependencies should work if you change your config.yml to just run your local archimedes, instead of production? i.e.

```
:archimedes_run_image: archimedes
```

But, I think this is a great idea! Should definitely be doable -- do you imagine this would be a different button that shows up in development, i.e. run-on-latest?

**Comment by dtm2451** [comment]
I'd need to update the lines below too?

From
```
  :archimedes_run_image: etnaagent/archimedes
  :archimedes_interpreters:
    :r: etnaagent/archimedes-r:latest
    :node: etnaagent/archimedes-node:latest
    :python: etnaagent/archimedes:latest
```

To
```
  :archimedes_run_image: archimedes
  :archimedes_interpreters:
    :r: archimedes-r:latest
    :node: archimedes-node:latest
    :python: archimedes:latest
```

or just the one line?

**Comment by coleshaw** [comment]
Yes, I think all lines like that would let the "Update dependencies" button to capture the local dev versions accurately. Might try `archimedes:latest` on the `archimedes_run_image` one too, to make sure you capture the latest one you build.

**Comment by dtm2451** [comment]
> do you imagine this would be a different button that shows up in development, i.e. run-on-latest?
Yea, as a button could be great!  DEf some control mechanism needed... I tend to want this behavior as the default, but it would need to be able to be turned off for testing of the image-pinning system.
