### ISSUE TITLE
Metis: Make Magma bucket copyable ?

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#997]
This would greatly help things like the GNE ETL, or possibly also support a Magma view inside of Metis.

One thing that we can't handle well is that Magma does not clean up its bucket. Generally should be okay, but there might be cruft (either someone deleted a file link, or reduced the number of items in a file_collection), so you would have to always fetch records and file / file_collection attributes from Magma first, and then run any sort of copy command. Do not copy blindly.

Perhaps related or duplicate of #894 ?

**Comment by graft** [comment]
Yeah given the old files and also the unreliability of parsing the filenames to determine how it is linked, it might be best to do this via #894

However, the question of "is it linked" came up the other day - this also involves Metis asking Magma about what is actually linked (although in this case it doesn't care where). Perhaps there is a better way for Metis to keep track of this information that is a little more reliable/doesn't involve phoning magma all the time?

**Comment by coleshaw** [comment]
Hm.... if Magma cleaned up its bucket, perhaps Metis could track?
